### ISSUE TITLE
Field metadata size is 2

### ISSUE THREAD

**Issue by vashchenkov** [isopov/tarantool-java-driver#11]
I try to use SQL syntax but got an error.

> Exception in thread "main" com.sopovs.moradanen.tarantool.core.TarantoolException: Field metadata size is 2
	at com.sopovs.moradanen.tarantool.SqlResult.getSize(SqlResult.java:41)
	at com.sopovs.moradanen.tarantool.SqlResult.<init>(SqlResult.java:20)
	at com.sopovs.moradanen.tarantool.TarantoolClientImpl.getSingleResult(TarantoolClientImpl.java:143)
	at com.sopovs.moradanen.tarantool.TarantoolClientImpl.execute(TarantoolClientImpl.java:158)
	at com.sopovs.moradanen.tarantool.jdbc.TarantoolStatement.executeQuery(TarantoolStatement.java:22)
	at com.sopovs.moradanen.tarantool.jdbc.TarantoolStatement.executeQuery(TarantoolStatement.java:8)
	at com.sopovs.moradanen.tarantool.samples.jdbc.JdbcSample.main(JdbcSample.java:19)

I've create a space from lua file

> local users_space = box.schema.space.create('ACTIVE_SESSIONS', {
        if_not_exists = true
    })
    users_space:format({
        {name='SESSION_ID', type = 'string'},
        {name='USER_ID', type='integer'}
    })
    users_space:create_index('primary_session_id', {
        if_not_exists = true,
        type = 'hash',
        unique = true,
        parts = {'SESSION_ID'}
    })
    users_space:create_index('secondary_user_id', {
        if_not_exists = true,
        type = 'tree',
        unique = true,
        parts = {'USER_ID'}
    })

And after that I call from JdbcSample 
>st.executeQuery("SELECT * FROM active_sessions where session_id='Hello World!'"))

And got the error. 

If call this query from Tarantool, I've got correct result
>\- metadata:
  \- name: SESSION_ID
    type: string
  \- name: USER_ID
    type: integer
  rows:
  \- ['HELLO WORLD!!!', 1234]

**Comment by isopov** [comment]
- Fixed in 6e7e0c3
- This connector is not official and not used anywhere - use it at your own risk!
